@startuml
left to right direction
skinparam packageStyle rectangle
actor Заказчик
actor Менеджер
rectangle Заказ {
  Заказчик -- (заказ)
  (заказ) .> (оплата) : включает
  (консультация) .> (заказ) : дополняет
  (заказ) -- Менеджер
}
@enduml
