@startuml
|Пользователь|
start
partition Регистрация/авторизация {
    if (Существует ли аккаунт у пользователя?) then(да)
            :Авторизация на сайте;
        else (нет)
        :Регистрация на сайте;
        :Авторизация на сайте;
    endif
    |Система|
        :Подтверждение учетных данных;
}
partition Оформление заказа {
    |Пользователь|
    :Выбор товаров;
    :Добавление в корзину;
    :Оформление заказа;
    :Выбор способа доставки;
    :Выбор способа оплаты;
}
partition Проверка наличия товара на складе {
    |Система|
    :Проверка наличия на складе;
    if (Есть ли товар на складе?) then(да)
        else (нет)
        :Уведомление клиента;
        |Пользователь|
        switch (Что сделать с недостающим товаром?) 
        case ( )
            :Удаление недостающего товара;
        case ( )
            :Выбор альтернативного товара;
        case ( )
            :Ожидание поступления товара;
            |Система|
            :Уведомление о поступлении;
            |Пользователь|
            :Подтверждение заказа;
        endswitch
            endif
}
    |Пользователь|
    :Ввод промокода;
    |Система|
    :Проверка условия использования скидки;
    switch (Корректен ли промокод?) 
        case ( )
            :Неверный промокод;
        case ( )
            :Превышен лимит испольования промокода;
        case ( )
            :Промокод не действует на выбранные товары;    
        endswitch
    :Уведомление клиенту о некорректности промокода;
    |Пользователь|
    switch ( ) 
        case ( )
            :Ввести промокод заново;
        case ( )
            :Пропустить ввод промокода;
    endswitch        
    |Система|        
    :Обновление суммы заказа;
    fork
    :Выбор способа оплаты;
    |Система|
    :Проверка платежные детали;
    fork again
    |Система|
    :Уведомление склада о необходимости собрать заказ;
    |Сотрудники склада|
    :Комплектация заказа;
    |Система|
    end fork
    |Система|
if (Оплата прошла успешно) then(да)
    :Генерация счет-фактуры;
    :Уведомление клиенту о подтверждении заказа;
    :Обновление статуса заказа "Отправлен";
        else (нет)
         switch ( ) 
        case ( )
            :Недостаточно средств;
        case ( )
            :Неверные платежные данные;
        case ( )
            :Платежная система недоступна;
        endswitch
        :Уведомление клиенту о проблеме с платежом;
        :Предложение клиенту повторить попытку или изменить способ оплаты;
        if (Клиента устраиваниет решение?) then(да)
    |Пользователь|
    switch ( ) 
        case ( )
            :Повтор попытки;
        case ( )
            :Измение способа оплаты;
        endswitch
        else (нет)
        |Система|
        :Заказ отменяется;
        :Клиенту возвращаются средства, если были списаны;
    endif
    endif
   fork
    |Пользователь|
    :Получение уведомлений о каждом изменеии статуса;
    fork again
    |Система|
    :Обновление статуса заказа по мере его движения;
    end fork
    stop
